// docs/blur-reveal/demo-speed.tsx
import { BlurReveal } from "@/registry/spell-ui/blur-reveal";

export function Demo() {
  return (
    <div className="flex flex-col gap-8 *:flex-col">
      <div>
        <p className="font-mono text-sm text-muted-foreground">SLOW (0.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={0.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">NORMAL (1.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={1.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">FAST (2)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={2} inView>
          You can just ship things.
        </BlurReveal>
      </div>
    </div>
  );
}

// docs/special-text/demo-speed.vue
<script setup lang="ts">
import { SpecialText } from "@/components/ui"
</script>

<template>
  <div
    class="flex flex-col gap-4"
  >
    <div
      class="flex items-center gap-4"
    >
      <span
        class="text-sm text-muted-foreground w-20 font-mono"
      >
        FAST:
      </span>
      <SpecialText
        :speed='10'
        class="text-lg"
        in-view
      >
        FAST ANIMATION
      </SpecialText>
    </div>
    <div
      class="flex items-center gap-4"
    >
      <span
        class="text-sm text-muted-foreground w-20 font-mono"
      >
        NORMAL:
      </span>
      <SpecialText
        :speed='20'
        class="text-lg"
        in-view
      >
        NORMAL SPEED
      </SpecialText>
    </div>
    <div
      class="flex items-center gap-4"
    >
      <span
        class="text-sm text-muted-foreground w-20 font-mono"
      >
        SLOW:
      </span>
      <SpecialText
        :speed='40'
        class="text-lg"
        in-view
      >
        SLOW MOTION
      </SpecialText>
    </div>
  </div>
</template>
