// docs/flow-button/demo-sizes.vue
<script setup lang="ts">
import { FlowButton } from "@/components/ui"
</script>

<template>
  <div
    class="flex items-center gap-4"
  >
    <FlowButton
      size="sm"
    >
      Small
    </FlowButton>
    <FlowButton
      size="default"
    >
      Default
    </FlowButton>
    <FlowButton
      size="lg"
    >
      Large
    </FlowButton>
  </div>
</template>

// docs/bars-spinner/demo-sizes.tsx
import { BarsSpinner } from "@/registry/spell-ui/bars-spinner";

export default function BarsSpinnerDemoSizes() {
  return (
    <div className="flex items-center gap-4">
      <BarsSpinner size={16} />
      <BarsSpinner size={20} />
      <BarsSpinner size={24} />
      <BarsSpinner size={32} />
    </div>
  );
}
