// components/app-sidebar.tsx
"use client";

import * as React from "react";

import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/components/ui/sidebar";
import { DocSchema } from "@/lib/types";
import Link from "next/link";
import { usePathname } from "next/navigation";

export function AppSidebar({
  docSchema,
  ...props
}: React.ComponentProps<typeof Sidebar> & {
  docSchema: DocSchema;
}) {
  const pathname = usePathname();
  const { toggleSidebar, isMobile } = useSidebar();
  const data = {
    navMain: docSchema,
  };

  return (
    <Sidebar className="mt-14" {...props}>
      {/* mt-16 > for header height */}
      <SidebarContent
        className="max-h-[calc(100vh-100px)] overflow-y-auto"
        style={{
          maskImage:
            "linear-gradient(to bottom, transparent 0, rgba(0,0,0,0.2) 1rem, black 2rem, black calc(100% - 2rem), rgba(0,0,0,0.2) calc(100% - 1rem), transparent 100%)",
        }}
      >
        <div className="h-4 shrink-0" />
        {data.navMain.map((item) => (
          <SidebarGroup key={item.title}>
            <SidebarGroupLabel>{item.title}</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {item.items.map((item) => (
                  <SidebarMenuItem key={item.title}>
                    <SidebarMenuButton
                      className="data-[active=true]:shadow-[0_0_0_1px_rgba(0,0,0,.08),_0px_2px_2px_rgba(0,0,0,.04)] data-[active=true]:not-dark:bg-white transition-all"
                      asChild
                      isActive={pathname === `/docs/${item.id}`}
                      onClick={() => {
                        if (isMobile) {
                          toggleSidebar();
                        }
                      }}
                    >
                      <Link href={`/docs/${item.id}`}>{item.title}</Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        ))}
        <div className="h-4 shrink-0" />
      </SidebarContent>
    </Sidebar>
  );
}

// vue/src/components/docs/AppSidebar.vue
<script setup lang="ts">
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from '@/components/ui'
import { navigate, useRoute } from '@/router'
import { useSidebar } from '@/composables/useSidebar'
import type { DocSchema } from '@/lib/types'

const props = defineProps<{
  docSchema: DocSchema
}>()

const route = useRoute()
const { isMobile, toggleSidebar } = useSidebar()

const goToDoc = (id: string) => {
  navigate(`/docs/${id}`)
  if (isMobile.value) {
    toggleSidebar()
  }
}
</script>

<template>
  <Sidebar class="mt-14">
    <SidebarContent
      class="max-h-[calc(100vh-100px)] overflow-y-auto"
      :style="{
        maskImage: 'linear-gradient(to bottom, transparent 0, rgba(0,0,0,0.2) 1rem, black 2rem, black calc(100% - 2rem), rgba(0,0,0,0.2) calc(100% - 1rem), transparent 100%)',
      }"
    >
      <div class="h-4 shrink-0" />
      <SidebarGroup v-for="group in props.docSchema" :key="group.title">
        <SidebarGroupLabel>{{ group.title }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in group.items" :key="item.id">
              <SidebarMenuButton
                class="data-[active=true]:shadow-[0_0_0_1px_rgba(0,0,0,.08),_0px_2px_2px_rgba(0,0,0,.04)] data-[active=true]:not-dark:bg-white transition-all"
                :is-active="route.name === 'doc' && route.id === item.id"
                @click="goToDoc(item.id)"
              >
                <span>{{ item.title }}</span>
              </SidebarMenuButton>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
      <div class="h-4 shrink-0" />
    </SidebarContent>
  </Sidebar>
</template>
