// components/mobile-nav.tsx
"use client";

import * as React from "react";
import Link, { type LinkProps } from "next/link";
import { useRouter, usePathname } from "next/navigation";

import { cn } from "@/lib/utils";
import { DocSchema } from "@/lib/types";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

export function MobileNav({
  docSchema,
  className,
}: {
  docSchema: DocSchema;
  className?: string;
}) {
  const [open, setOpen] = React.useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="ghost"
          className={cn(
            "h-8 touch-manipulation items-center justify-start gap-2.5 !p-0 hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 active:bg-transparent dark:hover:bg-transparent",
            className
          )}
        >
          <div className="relative flex h-8 w-4 items-center justify-center">
            <div className="relative size-4">
              <span
                className={cn(
                  "bg-foreground absolute left-0 block h-0.5 w-4 transition-all duration-100",
                  open ? "top-[0.45rem] -rotate-45" : "top-1"
                )}
              />
              <span
                className={cn(
                  "bg-foreground absolute left-0 block h-0.5 w-4 transition-all duration-100",
                  open ? "top-[0.45rem] rotate-45" : "top-2.5"
                )}
              />
            </div>
            <span className="sr-only">Toggle Menu</span>
          </div>
        </Button>
      </PopoverTrigger>
      <PopoverContent
        className="bg-background/90 no-scrollbar h-(--available-height) w-(--available-width) overflow-y-auto rounded-none border-none p-0 shadow-none backdrop-blur duration-100"
        align="start"
        side="bottom"
        alignOffset={-16}
        sideOffset={14}
      >
        <div className="flex flex-col gap-12 overflow-auto px-4 py-6">
          <div className="flex flex-col gap-8">
            {docSchema.map((group, index) => (
              <div key={index} className="flex flex-col gap-4">
                <div className="text-muted-foreground text-sm font-medium">
                  {group.title}
                </div>
                <div className="flex flex-col gap-3">
                  {group.items.map((item) => (
                    <MobileLink
                      key={item.id}
                      href={`/docs/${item.id}`}
                      onOpenChange={setOpen}
                    >
                      {item.title}
                    </MobileLink>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
}

function MobileLink({
  href,
  onOpenChange,
  className,
  children,
  ...props
}: LinkProps & {
  onOpenChange?: (open: boolean) => void;
  children: React.ReactNode;
  className?: string;
}) {
  const router = useRouter();
  const pathname = usePathname();
  const isActive = pathname === href;

  return (
    <Link
      href={href}
      onClick={() => {
        router.push(href.toString());
        onOpenChange?.(false);
      }}
      className={cn(
        "text-2xl font-medium transition-colors",
        isActive && "text-primary",
        className
      )}
      {...props}
    >
      {children}
    </Link>
  );
}

export default MobileNav;

// vue/src/components/docs/MobileNav.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Button, Popover, PopoverContent, PopoverTrigger } from '@/components/ui'
import { cn } from '@/lib/utils'
import AppLink from '@/components/AppLink.vue'
import type { DocSchema } from '@/lib/types'

defineProps<{
  docSchema: DocSchema
  class?: string
}>()

const open = ref(false)
</script>

<template>
  <Popover :open="open" @update:open="open = $event">
    <PopoverTrigger as-child>
      <Button
        variant="ghost"
        :class="
          cn(
            'h-8 touch-manipulation items-center justify-start gap-2.5 !p-0 hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 active:bg-transparent dark:hover:bg-transparent',
            $props.class,
          )
        "
      >
        <div class="relative flex h-8 w-4 items-center justify-center">
          <div class="relative size-4">
            <span
              :class="
                cn(
                  'bg-foreground absolute left-0 block h-0.5 w-4 transition-all duration-100',
                  open ? 'top-[0.45rem] -rotate-45' : 'top-1',
                )
              "
            />
            <span
              :class="
                cn(
                  'bg-foreground absolute left-0 block h-0.5 w-4 transition-all duration-100',
                  open ? 'top-[0.45rem] rotate-45' : 'top-2.5',
                )
              "
            />
          </div>
          <span class="sr-only">Toggle Menu</span>
        </div>
      </Button>
    </PopoverTrigger>

    <PopoverContent
      class="bg-background/90 h-(--radix-popover-content-available-height) w-(--radix-popover-content-available-width) overflow-y-auto rounded-none border-none p-0 shadow-none backdrop-blur duration-100"
      align="start"
      side="bottom"
      :align-offset="-16"
      :side-offset="14"
    >
      <div class="flex flex-col gap-12 overflow-auto px-4 py-6">
        <div class="flex flex-col gap-8">
          <div v-for="group in docSchema" :key="group.title" class="flex flex-col gap-4">
            <div class="text-sm font-medium text-muted-foreground">
              {{ group.title }}
            </div>
            <div class="flex flex-col gap-3">
              <AppLink
                v-for="item in group.items"
                :key="item.id"
                :to="`/docs/${item.id}`"
                class="text-2xl font-medium transition-colors"
                @click="open = false"
              >
                {{ item.title }}
              </AppLink>
            </div>
          </div>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>
