// docs/blur-reveal/demo-speed.tsx
import { BlurReveal } from "@/registry/spell-ui/blur-reveal";

export function Demo() {
  return (
    <div className="flex flex-col gap-8 *:flex-col">
      <div>
        <p className="font-mono text-sm text-muted-foreground">SLOW (0.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={0.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">NORMAL (1.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={1.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">FAST (2)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={2} inView>
          You can just ship things.
        </BlurReveal>
      </div>
    </div>
  );
}

// docs/words-stagger/demo-speed.vue
<script setup lang="ts">
import { WordsStagger } from "@/components/ui"
</script>

<template>
  <div
    class="flex flex-col gap-8"
  >
    <div
      class="space-y-2"
    >
      <p
        class="text-sm font-mono text-muted-foreground"
      >
        SLOW (1)
      </p>
      <WordsStagger
        :speed='1'
        class="text-xl font-medium"
        in-view
      >
        You can just ship things.
      </WordsStagger>
    </div>
    <div
      class="space-y-2"
    >
      <p
        class="text-sm font-mono text-muted-foreground"
      >
        NORMAL (0.5)
      </p>
      <WordsStagger
        :speed='0.5'
        class="text-xl font-medium"
        in-view
      >
        You can just ship things.
      </WordsStagger>
    </div>
    <div
      class="space-y-2"
    >
      <p
        class="text-sm font-mono text-muted-foreground"
      >
        FAST (0.3)
      </p>
      <WordsStagger
        :speed='0.3'
        class="text-xl font-medium"
        in-view
      >
        You can just ship things.
      </WordsStagger>
    </div>
  </div>
</template>
