// docs/blur-reveal/demo-speed.tsx
import { BlurReveal } from "@/registry/spell-ui/blur-reveal";

export function Demo() {
  return (
    <div className="flex flex-col gap-8 *:flex-col">
      <div>
        <p className="font-mono text-sm text-muted-foreground">SLOW (0.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={0.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">NORMAL (1.5)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={1.5} inView>
          You can just ship things.
        </BlurReveal>
      </div>
      <div>
        <p className="font-mono text-sm text-muted-foreground">FAST (2)</p>
        <BlurReveal className="tracking-tight text-2xl font-medium" speedReveal={2} inView>
          You can just ship things.
        </BlurReveal>
      </div>
    </div>
  );
}

// docs/blur-reveal/demo-speed.vue
<script setup lang="ts">
import { BlurReveal } from "@/components/ui"
</script>

<template>
  <div
    class="flex flex-col gap-8 *:flex-col"
  >
    <div>
      <p
        class="font-mono text-sm text-muted-foreground"
      >
        SLOW (0.5)
      </p>
      <BlurReveal
        class="tracking-tight text-2xl font-medium"
        :speed-reveal='0.5'
        in-view
      >
        You can just ship things.
      </BlurReveal>
    </div>
    <div>
      <p
        class="font-mono text-sm text-muted-foreground"
      >
        NORMAL (1.5)
      </p>
      <BlurReveal
        class="tracking-tight text-2xl font-medium"
        :speed-reveal='1.5'
        in-view
      >
        You can just ship things.
      </BlurReveal>
    </div>
    <div>
      <p
        class="font-mono text-sm text-muted-foreground"
      >
        FAST (2)
      </p>
      <BlurReveal
        class="tracking-tight text-2xl font-medium"
        :speed-reveal='2'
        in-view
      >
        You can just ship things.
      </BlurReveal>
    </div>
  </div>
</template>
