// docs/kbd/demo-symbols.tsx
import { Kbd } from "@/registry/spell-ui/kbd";

export function Demo() {
  return (
    <div className="flex flex-wrap gap-4">
      <Kbd keys={["command"]} listenToKeyboard />
      <Kbd keys={["control"]} listenToKeyboard />
      <Kbd keys={["alt"]} listenToKeyboard />
      <Kbd keys={["up"]} listenToKeyboard />
      <Kbd keys={["down"]} listenToKeyboard />
      <Kbd keys={["left"]} listenToKeyboard />
      <Kbd keys={["right"]} listenToKeyboard />
    </div>
  );
}

// docs/kbd/demo-symbols.vue
<script setup lang="ts">
import { Kbd } from "@/components/ui"
</script>

<template>
  <div
    class="flex flex-wrap gap-4"
  >
    <Kbd
      :keys='["command"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["control"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["alt"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["up"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["down"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["left"]'
      listen-to-keyboard
    />
    <Kbd
      :keys='["right"]'
      listen-to-keyboard
    />
  </div>
</template>
